module.exports = {
  ENV_TOKEN_VAR: "GOOGLE_DOCS_TOKEN",
  DEFAULT_OPTIONS: {
    createPages: false,
    debug: false,
    defaults: {},
    demoteHeadings: true,
    depth: undefined,
    folder: undefined,
    ignore: [],
    images: {},
    skipCodes: false,
    skipFootnotes: false,
    skipHeadings: false,
    skipImages: false,
    skipLists: false,
    skipQuotes: false,
    skipTables: false,
  },
  DEFAULT_TEMPLATE: "page",
}
